apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  namespace: photoprism
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  volumeName: photoprism-database-pv
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-pvc
  namespace: photoprism
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  volumeName: photoprism-storage-pv
  resources:
    requests:
      storage: 400Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: originals-pvc
  namespace: photoprism
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  volumeName: photoprism-originals-pv
  resources:
    requests:
      storage: 2000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: import-pvc
  namespace: photoprism
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  volumeName: photoprism-import-pv
  resources:
    requests:
      storage: 3000Gi
